
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

export JAVA_HOME='/usr/lib/jvm/java-8-oracle'

export PATH=/opt/hbase/bin:$PATH

export PS1='\u\[\e[38;5;237m\]@\[\e[0m\]\[\e[38;5;35m\]\h\[\e[0m\]\[\e[38;5;237m\]:\[\e[0m\]\[\e[1;34m\]\w\[\e[0m\]\[\e[38;5;237m\]\$\[\e[0m\] '

